# Generated by Django 2.2.3 on 2019-08-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.ImageField(default='none.jpg', upload_to='images/'),
        ),
    ]
