# Generated by Django 2.2.4 on 2019-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190812_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookimage',
            field=models.ImageField(default='images/none.jpg', upload_to='images/'),
        ),
    ]
